//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mağza_Ürün_Takip_Sistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsatislar
    {
        public int Id { get; set; }
        public Nullable<int> Urun { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblpersonel tblpersonel { get; set; }
        public virtual tblurunler tblurunler { get; set; }
    }
}
